# Learnable Parameters

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation

C:\Users\sem.onyalo\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
model = Sequential([
    Dense(3, input_shape=(2,), activation='relu'),
    Dense(2, activation='softmax')
])

In [3]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 8         
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.get_weights()

[array([[-0.25716728,  0.72029257, -1.0651933 ],
        [-0.21416461,  0.7165332 ,  0.36128187]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.8443507 , -0.87415826],
        [-0.30569977,  0.90469646],
        [ 0.57854843, -0.26650012]], dtype=float32),
 array([0., 0.], dtype=float32)]

# Learnable Parameters in a CNN

In [5]:
from keras.layers.core import Flatten
from keras.layers.convolutional import *
from keras.layers.pooling import *

In [6]:
model = Sequential([
    Conv2D(2, kernel_size=(3,3), input_shape=(20,20,3), activation='relu', padding='same'),
    Conv2D(3, kernel_size=(3,3), activation='relu', padding='same'),
    Flatten(),
    Dense(2, activation='softmax')
])

In [7]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 20, 20, 2)         56        
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 20, 20, 3)         57        
_________________________________________________________________
flatten_1 (Flatten)          (None, 1200)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 2402      
Total params: 2,515
Trainable params: 2,515
Non-trainable params: 0
_________________________________________________________________


## Remove zero-padding

In [8]:
no_padding_model = Sequential([
    Conv2D(2, kernel_size=(3,3), input_shape=(20,20,3), activation='relu'),
    Conv2D(3, kernel_size=(3,3), activation='relu'),
    Flatten(),
    Dense(2, activation='softmax')
])

In [9]:
no_padding_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 18, 18, 2)         56        
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 16, 16, 3)         57        
_________________________________________________________________
flatten_2 (Flatten)          (None, 768)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 1538      
Total params: 1,651
Trainable params: 1,651
Non-trainable params: 0
_________________________________________________________________


## Add max pooling

In [10]:
pooling_model = Sequential([
    Conv2D(2, kernel_size=(3,3), input_shape=(20,20,3), activation='relu', padding='same'),
    Conv2D(3, kernel_size=(3,3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(2,2), strides=2),
    Flatten(),
    Dense(2, activation='softmax')
])

In [11]:
pooling_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 20, 20, 2)         56        
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 20, 20, 3)         57        
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 10, 3)         0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 300)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 602       
Total params: 715
Trainable params: 715
Non-trainable params: 0
_________________________________________________________________
