In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation

C:\Users\sem.onyalo\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
model = Sequential([
    Dense(4, input_shape=(1,), activation='relu', use_bias=True, bias_initializer='zeros'),
    Dense(2, activation='softmax')
])

In [3]:
model.get_weights()

[array([[ 0.5946313 ,  0.29302502,  0.23781872, -0.39044356]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[ 0.25278807,  0.15640426],
        [ 0.6714175 , -0.6382184 ],
        [ 0.27332926,  0.2303927 ],
        [ 0.7707646 , -0.06389523]], dtype=float32),
 array([0., 0.], dtype=float32)]